-- source_db.`user` definition
CREATE TABLE `user` (
  `ID` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `STUDENT_NO` varchar(50) NOT NULL COMMENT '学号',
  `NAME` varchar(100) NOT NULL COMMENT '姓名',
  `CLASS` varchar(50) DEFAULT NULL COMMENT '班级',
  `SEX` tinyint(1) DEFAULT '1' COMMENT '性别：1-男，2-女',
  `AGE` int DEFAULT NULL COMMENT '年龄',
  `STUDENT_INFO` longtext COMMENT '学生信息',
  `CREATED_TIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_STUDENT_NO` (`STUDENT_NO`),
  KEY `IDX_NAME` (`NAME`),
  KEY `IDX_CLASS` (`CLASS`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户表';